# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FilteredImageUpload' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FilteredImageUpload
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Storage', '~> 5.15.0'
  pod 'Firebase/Database', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'

end

target 'FilteredImageUpload-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FilteredImageUpload-tvOS

  target 'FilteredImageUpload-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
